project_id = "jgkclkyjjfrlperamzrz"

[functions.sync-crew-to-sheets]
verify_jwt = false

[functions.sync-all-data]
verify_jwt = false

[functions.sync-deliverables-to-sheets]
verify_jwt = false

[functions.pcloud-api]
verify_jwt = false

[functions.idrive-e2-api]
verify_jwt = false