export { default as ClientDetailSidebar } from './ClientDetailSidebar';
export type { SectionType } from './ClientDetailSidebar';
export { default as ClientHeroSection } from './ClientHeroSection';
export { default as LastActivitiesSummary } from './LastActivitiesSummary';
export { default as ChatComments } from './ChatComments';
export { default as QuotationDisplaySection } from './QuotationDisplaySection';
export { default as DashboardEventDetails } from './DashboardEventDetails';
export { EventDetailCard } from './EventDetailCard';
export { EventDetailsSummaryCard } from './EventDetailsSummaryCard';
export { FullScreenEventCard } from './FullScreenEventCard';
